---
ansible_virtualenv: "/home/liederbach/.virtualenvs/ansible2-modular"
ansible_python_interpreter: "/home/liederbach/.virtualenvs/ansible2-modular/bin/python"
ansible_private_key_file: "~/.ssh/jenkins_id_rsa"
ansible_user: "liederbach"
