---
- block:
    - block:
      - name: (Deploy) Finding all application code instances
        shell: "find {{remote_apps_app_root_releases}}/ -name {{app_uuid_prefix}}\\*"
        register: code_instances
      - name: (Deploy) Removing previous application code
        file:
          path: "{{item}}"
          state: absent
        with_items: "{{code_instances.stdout_lines}}"
        when:
          - app_uuid not in item
    - block:
        - name: (Deploy) Finding all application gunicorn configuration files
          shell: "find {{remote_gunicorn_confd}}/ -name {{app_uuid_prefix}}\\*"
          register: code_instances
        - name: (Deploy) Removing previous application gunicorn cofiguration files
          file:
            path: "{{item}}"
            state: absent
          with_items: "{{code_instances.stdout_lines}}"
          when:
            - app_uuid not in item
    - block:
        - name: (Deploy) Finding all application supervisor logs
          shell: "find {{remote_supervisor_log}}/ -name {{app_uuid_prefix}}\\*"
          register: code_instances
        - name: (Deploy) Removing previous application supervisor logs
          file:
            path: "{{item}}"
            state: absent
          with_items: "{{code_instances.stdout_lines}}"
          when:
            - app_uuid not in item
  tags:
    - deploy